namespace:
  name: demo
 
image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

service:
    type: ClusterIP
    port: 8111

replicaCount: 3

resources:
  requests:
    cpu: 50m
    memory: 256Mi

configmap:
  data: "version: alpine"

